stages:
  - deploy

build:
  stage: deploy
  tags:
    - chigisoft
    - shared
  only:
    - tags
  script:
    - echo "//git.chigisoft.dev/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish
